# Generated by Django 4.2.5 on 2023-09-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date',
            new_name='BirthDate',
        ),
    ]
